import pandas as pd
from matplotlib import pyplot as plt
sample__data=pd.read_csv('/content/corona.csv')
plt.figure(figsize=(15,9))
plt.plot(sample__data.Date,sample__data.China/10**6)
plt.plot(sample__data.Date,sample__data.India/10**6)
#plt.plot(sample__data.Date,sample__data.Hong Kong)
plt.plot(sample__data.Date,sample__data.Macau/10**6)
plt.plot(sample__data.Date,sample__data.USA/10**6)
plt.plot(sample__data.Date,sample__data.UAE/10**6)
plt.plot(sample__data.Date,sample__data.Australia/10**6)
plt.plot(sample__data.Date,sample__data.Cambodia/10**6)
plt.plot(sample__data.Date,sample__data.Canada/10**6)
plt.plot(sample__data.Date,sample__data.Finland/10**6)
plt.plot(sample__data.Date,sample__data.France/10**6)
plt.plot(sample__data.Date,sample__data.Germany/10**6)
plt.plot(sample__data.Date,sample__data.Japan/10**6)
plt.plot(sample__data.Date,sample__data.Malaysia/10**6)
plt.plot(sample__data.Date,sample__data.Nepal/10**6)
plt.plot(sample__data.Date,sample__data.Philippines/10**6)
plt.plot(sample__data.Date,sample__data.Singapore/10**6)
plt.plot(sample__data.Date,sample__data.Taipei/10**6)
plt.plot(sample__data.Date,sample__data.Thailand/10**6)
plt.legend(['China','Macau','Taipei','Japan','South Korea','Viet Nam','Singapore','Australia','Malaysia','Cambodia','Philippines','Thailand','Nepal','Sri Lanka','India','USA','Canada','France','Finland','Germany','UAE'])
plt.xlabel('Date',size=20)
plt.ylabel('Infected count/10^6',size=20)
plt.show()